version: '3.7'

services:

  stock-dashboard:
    container_name: stock-dashboard
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true